In [1]:
import os
os.environ['JAX_PLATFORMS'] = 'cpu'

import jax.numpy as jnp
from jax import random

from pidon.model.antiderivative import MLP

In [2]:
# MLP layers
layers = [1, 3, 2]

# Network initialization and evaluation functions
mlp_init, mlp_apply = MLP(layers, activation=jnp.tanh)

# Initialize
params = mlp_init(rng_key = random.PRNGKey(1234))

In [6]:
params

[(Array([[-0.19568045,  0.61569846,  0.5995719 ]], dtype=float32),
  Array([0., 0., 0.], dtype=float32)),
 (Array([[-0.51355344,  0.14883885],
         [-1.7371219 ,  0.43907484],
         [ 0.17296094, -0.40999344]], dtype=float32),
  Array([0., 0.], dtype=float32))]

In [12]:
# (batch_size, 1)
inputs = jnp.ones((5, 1))
print(inputs.shape)
print(inputs)

(5, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [13]:
# (batch_size, 2)
outputs = mlp_apply(params, inputs)
print(outputs.shape)
print(outputs)

(5, 2)
[[-0.76009667 -0.00815228]
 [-0.76009667 -0.00815228]
 [-0.76009667 -0.00815228]
 [-0.76009667 -0.00815228]
 [-0.76009667 -0.00815228]]
